name: CI

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Create Wrath Classic Package
        uses: BigWigsMods/packager@master
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/') }}
        with:
          args: -g wrath -p 468754 -w 25934 -a WqKQbyGx
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create BCC Package
        uses: BigWigsMods/packager@master
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/') }}
        with:
          args: -g bcc -p 468754 -w 25934 -a WqKQbyGx
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        if: ${{ success() && github.event_name != 'pull_request' && contains(github.ref, 'tags/') }}
        with:
          args: -g classic -p 468754 -w 25934 -a WqKQbyGx
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}